import streamlit as st
from openai import OpenAI
import os
from dotenv import load_dotenv
load_dotenv()

# Load API key from environment variable
client = OpenAI()

def check_content(model_name, prompt, input_text):
    completion = client.chat.completions.create(
    model="gpt-4o-mini",
    messages=[
        {"role": "system", "content": prompt},
        {"role": "user", "content": input_text}
    ]
    )
    return completion.choices[0].message.content

model_name = "gpt-4o-mini"
prompt = "Determine if the following content is written by AI or a human, If the content is written by human, you should reply 'The content is written by a human.' If the content is generated by AI, you should reply 'The content is written by AI."

# Streamlit interface
st.title("AI vs Human Text GPT-4o-mini Detector")
st.write("Enter a text below to check whether it was generated by AI or written by a human.")

input_text = st.text_area("Input Text")

if st.button("Check"):
    result = check_content(model_name, prompt, input_text)
    st.write(result)